# Site settings
title: Pramod - Living Startups life
email: pramod_sharma@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Here I will discuss about my Development Experience in general and
  more specifically about startups, Ruby On Rails, Core JavaScript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  pramod-sharma
permalink: :year/:month/:title
# Build settings
markdown: kramdown
